name: Bug Report
description: Report a bug
type: Bug

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Don't forget about spoilers if you attach screenshots/videos.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: A minimal description of how to reproduce the bug.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: If applicable, describe what you expected to happen.

  - type: textarea
    id: logs
    attributes:
      label: Stack trace
      description: If applicable, include a stack trace of the error. See in devtools console.
      render: text
