name: Bug Report
description: Report a bug
# type: Bug

body:
  - type: markdown
    attributes:
      value: |
        Please give the issue a title that describes what and where you've found the bug. Be less abstract and more specific.
        Good:
          1. \<action\> causes app to crash
          2. Tables: Image enlarges when neightboring cell width changed
          3. Firefox: Table cells may be too narrow making content to overflow
          
        Bad:
          1. App crashes with an error \<any unrelated error\> 
          2. Image issues in tables
          3. Tables are displayed incorrectly in the browser
            
        If there is a related issue, please reference it in the description.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Specify the scope of the issue to help us triage the issue quicker
      default: 7
      options:
        - 'Desktop App (macOS, windows, linux)'
        - 'Web App'
        - 'Editor (wysiwyg, markdown)'
        - 'UI/UX'
        - 'Git (storages, push/pull, etc.)'
        - 'Docportal'
        - 'Static/CLI'
        - 'Other'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear description of what the bug is. Screenshots or videos can be included to describe the issue more precisely.
        Also include the steps to reproduce the issue, stacktrace or piece of markdown causing problems.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior (Optional)
      description: If applicable, describe what you expected to happen.
